-- we don't know how to generate schema CU_ONLINE_DW (class Schema) :(
create or replace table ERROR_TABLE
(
	ROW_NR DECIMAL(18),
	ERROR_TEXT VARCHAR(1000) UTF8,
	TRUNCATED BOOLEAN,
	CSV_DATA VARCHAR(2000000) UTF8
)
/

create or replace table ONLINE_STATUS
(
	PERSON_ID DECIMAL(18),
	TERM_SD VARCHAR(10) UTF8,
	ACAD_CAR_CD VARCHAR(10) UTF8,
	LAST_NM VARCHAR(255) UTF8,
	FIRST_NM VARCHAR(255) UTF8,
	PRE_CU_EMAIL VARCHAR(255) UTF8,
	DEN_EMAIL VARCHAR(255) UTF8,
	ACAD_LVL_SD VARCHAR(50) UTF8,
	ACAD_PROG_CD VARCHAR(50) UTF8,
	ACAD_PROG_LD VARCHAR(255) UTF8,
	ACAD_PLAN_CD VARCHAR(50) UTF8,
	ACAD_PLAN_LD VARCHAR(255) UTF8,
	ACAD_SPLAN_CD VARCHAR(50) UTF8,
	CUR_GPA_PTS DECIMAL(18,3),
	CUM_GPA_PTS DECIMAL(18,3),
	TAKEN_PRGRS_UNIT DECIMAL(18),
	PASSD_PRGRS_UNIT DECIMAL(18),
	TOT_PASSD_PRGRSS DECIMAL(18),
	ONLINE_COUNT_CURRENT_TERM DECIMAL(18),
	TRADITIONAL_COUNT_CURRENT_TERM DECIMAL(18),
	CURRENT_TERM_STATUS VARCHAR(255) UTF8,
	ONLINE_COUNT_OVER_CAREER DECIMAL(18),
	TRADITIONAL_COUNT_OVER_CAREER DECIMAL(18),
	CAREER_STATUS VARCHAR(255) UTF8
)
/

create or replace table ONLINE_STATUS_1718
(
	PERSONID VARCHAR(255) UTF8,
	ONLINE_COURSE_COUNT VARCHAR(255) UTF8,
	TRAD_COURSE_COUNT VARCHAR(255) UTF8
)
/

create or replace table GRADS1718
(
	TERM VARCHAR(255) UTF8,
	LASTNM VARCHAR(255) UTF8,
	MIDDLENM VARCHAR(255) UTF8,
	FIRSTNM VARCHAR(255) UTF8,
	PERSONID VARCHAR(255) UTF8,
	FERPAFLG VARCHAR(255) UTF8,
	CAREER VARCHAR(255) UTF8,
	ACAD_PROGRAM VARCHAR(255) UTF8,
	DEGREE VARCHAR(255) UTF8
)
/

create or replace table COGNOS_COURSE_LISTS
(
	TERM_CD VARCHAR(255) UTF8,
	TERM_SD VARCHAR(255) UTF8,
	SBJCT_CD VARCHAR(255) UTF8,
	CATALOG_NBR VARCHAR(255) UTF8,
	CLASS_SECTION_CD VARCHAR(255) UTF8,
	CLASS_NUM VARCHAR(255) UTF8,
	CRSE_ID VARCHAR(255) UTF8,
	CRSE_LD VARCHAR(255) UTF8,
	CAMPUS_CD VARCHAR(255) UTF8,
	ACAD_ORG_CD VARCHAR(255) UTF8,
	ACAD_GRP_CD VARCHAR(255) UTF8,
	ACAD_CAR_CD VARCHAR(255) UTF8,
	ENRL_TOT VARCHAR(255) UTF8,
	UNITS_MAXIMUM VARCHAR(255) UTF8,
	INSTRCTN_MODE_CD VARCHAR(255) UTF8
)
/

create or replace table COGNOS_COURSE_LISTS_PRD
(
	ACADEMIC_YEAR DECIMAL(18),
	TERM_CD DECIMAL(18),
	TERM_SD VARCHAR(255) UTF8,
	SBJCT_CD VARCHAR(255) UTF8,
	CATALOG_NBR VARCHAR(255) UTF8,
	CLASS_SECTION_CD VARCHAR(255) UTF8,
	CLASS_NUM VARCHAR(255) UTF8,
	CRSE_ID VARCHAR(255) UTF8,
	CRSE_LD VARCHAR(255) UTF8,
	CAMPUS_CD VARCHAR(255) UTF8,
	ACAD_ORG_CD VARCHAR(255) UTF8,
	ACAD_GRP_CD VARCHAR(255) UTF8,
	ACAD_CAR_CD VARCHAR(255) UTF8,
	ENRL_TOT DECIMAL(18),
	UNITS_MAXIMUM DECIMAL(18,2),
	INSTRCTN_MODE_CD VARCHAR(255) UTF8
)
/

create view CU_ONLINE_DW.COURSE_ROLLUP_VIEW as
(
  select
   CAMPUS_CD,
   ACADEMIC_YEAR,
   TERM_CD,
   TERM_SD,
   INSTRCTN_MODE_CD,
   COUNT(1)                           as COURSE_COUNT,
   SUM(ENRL_TOT)                      as ENROLLMENTS,
   SUM(ENRL_TOT) * sum(UNITS_MAXIMUM) as CREDIT_HOURS

 from
   COGNOS_COURSE_LISTS_PRD
 group by
   CAMPUS_CD,
   ACADEMIC_YEAR,
   TERM_CD,
   TERM_SD,
   INSTRCTN_MODE_CD
 order by
   CAMPUS_CD,
   ACADEMIC_YEAR,
   TERM_CD,
   TERM_SD,
   INSTRCTN_MODE_CD
)
/
