-- we don't know how to generate schema CU_ONLINE_MARKETING_STG (class Schema) :(
create or replace table FACEBOOK_ADS
(
	ACCOUNT_ID DECIMAL(18),
	AD_ID DECIMAL(18),
	ADSET_ID DECIMAL(18),
	ADSET_NAME VARCHAR(255) UTF8,
	CAMPAIGN_ID DECIMAL(18),
	CAMPAIGN_NAME VARCHAR(255) UTF8,
	CLICKS DECIMAL(18),
	CPC DECIMAL(18,10),
	CPM DECIMAL(18,10),
	CPP DECIMAL(18,10),
	CTR DECIMAL(18,10),
	DATE_START DATE,
	DATE_END DATE,
	FREQUENCY DECIMAL(18,10),
	IMPRESSIONS DECIMAL(18),
	INLINE_LINK_CLICK_CTR DECIMAL(18,10),
	INLINE_LINK_CLICKS DECIMAL(18),
	OBJECTIVE VARCHAR(100) UTF8,
	REACH DECIMAL(18),
	SOCIAL_CLICKS DECIMAL(18),
	SOCIAL_IMPRESSIONS DECIMAL(18),
	SOCIAL_REACH DECIMAL(18),
	SOCIAL_SPEND DECIMAL(18,2),
	SPEND DECIMAL(18,2),
	TOTAL_ACTION_VALUE DECIMAL(18),
	TOTAL_ACTIONS DECIMAL(18),
	UNIQUE_CLICKS DECIMAL(18),
	UNIQUE_CTR DECIMAL(18,10),
	UNIQUE_SOCIAL_CLICKS DECIMAL(18)
)
/

create or replace table LINKEDIN_CAMPAIGNS
(
	ACCOUNT VARCHAR(100) UTF8,
	ID DECIMAL(18),
	CAMPAIGN_NAME VARCHAR(255) UTF8,
	OBJECTIVE_TYPE VARCHAR(100) UTF8,
	CREATED_DATE DATE,
	MODIFIED_DATE DATE,
	COST_TYPE VARCHAR(100) UTF8,
	DAILY_BUDGET DECIMAL(18,2),
	TOTAL_BUDGET_AMOUNT DECIMAL(18,2),
	CAMPAIGN_TYPE VARCHAR(100) UTF8,
	UNIT_COST_AMOUNT DECIMAL(18,2),
	CREATIVE_SELECTION VARCHAR(100) UTF8,
	START_DATE DATE,
	END_DATE DATE
)
/

create or replace table GOOGLE_ADWORDS
(
	AD_DATE DATE,
	CAMPAIGN_ID DECIMAL(18),
	CAMPAIGN_NAME VARCHAR(100) UTF8,
	ADGROUP_ID DECIMAL(18),
	ADGROUP_NAME VARCHAR(100) UTF8,
	ADGROUP_STATUS VARCHAR(50) UTF8,
	AD_TYPE VARCHAR(50) UTF8,
	DESCRIPTION VARCHAR(255) UTF8,
	HEADLINE VARCHAR(255) UTF8,
	AD_ID DECIMAL(18),
	AD_STATUS VARCHAR(50) UTF8,
	CLICKS DECIMAL(18),
	CONVERSION_RATE DECIMAL(18,10),
	CONVERSIONS DECIMAL(18),
	COST DECIMAL(18,2),
	COST_PER_CONVERSION DECIMAL(18,10),
	CLICK_THROUGH_RATE DECIMAL(18,10),
	ENGAGEMENT_RATE DECIMAL(18,10),
	ENGAGEMENTS DECIMAL(18),
	IMPRESSIONS DECIMAL(18),
	INTERACTIONS DECIMAL(18),
	PERCENT_INTERACTIONS_NEW DECIMAL(18,10),
	VIDEO_VIEWS DECIMAL(18)
)
/

create or replace table LINKEDIN_ADS
(
	CREATIVE_ID DECIMAL(18),
	CLICKS DECIMAL(18),
	AD_COMMENTS DECIMAL(18),
	COMPANY_PAGE_CLICKS DECIMAL(18),
	COST DECIMAL(18,2),
	IMPRESSIONS DECIMAL(18),
	FOLLOWS DECIMAL(18),
	SHARES DECIMAL(18),
	VIRAL_CLICKS DECIMAL(18),
	VIRAL_FOLLOWS DECIMAL(18),
	VIRAL_IMPRESSIONS DECIMAL(18),
	VIRAL_COMMENTS DECIMAL(18),
	VIRAL_SHARES DECIMAL(18),
	AD_DATE DATE
)
/

create or replace table LINKEDIN_CAMPAIGN_CREATIVE_LINK
(
	CAMPAIGN_ID DECIMAL(18),
	CREATIVE_ID DECIMAL(18),
	STATUS VARCHAR(100) UTF8,
	CREATED_DATE DATE,
	MODIFIED_DATE DATE
)
/

create or replace table ASK_NICELY_RESPONSES
(
	RESPONSE_ID DECIMAL(18),
	RESPONSE_DATE DATE,
	NAME VARCHAR(100) UTF8,
	SEGMENT VARCHAR(100) UTF8,
	EMAIL VARCHAR(100) UTF8,
	ANSWER DECIMAL(18)
)
/

create or replace table HUBSPOT_CONTACTS
(
	VID DECIMAL(18),
	FIRST_NAME VARCHAR(255) UTF8 default NULL,
	LAST_NAME VARCHAR(255) UTF8 default NULL,
	MODIFIED_DATE DATE
)
/

create or replace table HUBSPOT_CONTACTS_INFO
(
	VID DECIMAL(18),
	FIRST_NAME VARCHAR(100) UTF8,
	LAST_NAME VARCHAR(100) UTF8,
	CREATED_DATE DATE,
	LIFECYCLE_STAGE VARCHAR(100) UTF8,
	LIFECYCLE_STAGE_DATE DATE,
	CONVERSION_NAME VARCHAR(255) UTF8,
	CONVERSION_DATE DATE,
	NUM_PAGE_VIEWS DECIMAL(18),
	HOME_CITY VARCHAR(100) UTF8,
	HOME_STATE VARCHAR(100) UTF8,
	HOME_ZIP VARCHAR(10) UTF8,
	HUBSPOT_SCORE DECIMAL(18),
	TWITTER VARCHAR(100) UTF8,
	LINKED_IN VARCHAR(100) UTF8,
	LINKED_IN_BIO VARCHAR(255) UTF8,
	PHONE VARCHAR(50) UTF8,
	SPECIALIZATIONS VARCHAR(255) UTF8,
	EMAIL VARCHAR(100) UTF8,
	CU_EMAIL VARCHAR(100) UTF8,
	LEAD_STATUS VARCHAR(100) UTF8,
	EMAILS_SINCE_LAST_ENGAGEMENT VARCHAR(100) UTF8,
	RESIDENCY VARCHAR(50) UTF8,
	CU_ADMIT VARCHAR(50) UTF8,
	CLOSED_DATE DATE,
	LAST_MODIFIED_DATE DATE,
	KLOUTSCORE VARCHAR(50) UTF8,
	IMPORT_DATE DATE
)
/

create or replace table HUBSPOT_CONTACTS_ACADEMIC_PROGRAMS
(
	VID DECIMAL(18),
	ACADEMIC_PROGRAM VARCHAR(100) UTF8
)
/

create or replace table HUBSPOT_SOCIAL_POSTS
(
	POST_ID DECIMAL(18),
	CAMPAIGN_ID VARCHAR(100) UTF8,
	POST_CHANNEL VARCHAR(50) UTF8,
	CREATED_DATE DATE,
	POST_TITLE VARCHAR(255) UTF8,
	POST_URL VARCHAR(255) UTF8,
	CLICKS DECIMAL(18),
	LIKES DECIMAL(18),
	RETWEETS DECIMAL(18),
	REPLIES DECIMAL(18),
	ITERACTIONS DECIMAL(18)
)
/

create or replace table LINKEDIN_CAMPAIGNS_UPDATED
(
	ACCOUNT VARCHAR(100) UTF8,
	ID DECIMAL(18),
	CAMPAIGN_NAME VARCHAR(255) UTF8,
	OBJECTIVE_TYPE VARCHAR(100) UTF8,
	CREATED_DATE DATE,
	MODIFIED_DATE DATE,
	COST_TYPE VARCHAR(100) UTF8,
	DAILY_BUDGET DECIMAL(18,2),
	CAMPAIGN_TYPE VARCHAR(100) UTF8,
	UNIT_COST_AMOUNT DECIMAL(18,2),
	CREATIVE_SELECTION VARCHAR(100) UTF8
)
/

create or replace table HUBSPOT_CONTACTS_TEST
(
	VID DECIMAL(18),
	FIRST_NAME VARCHAR(255) UTF8 default NULL,
	LAST_NAME VARCHAR(255) UTF8 default NULL,
	MODIFIED_DATE DATE
)
/

create or replace table FACEBOOK_ADS_0818
(
	ACCOUNT_ID DECIMAL(18),
	AD_ID DECIMAL(18),
	ADSET_ID DECIMAL(18),
	ADSET_NAME VARCHAR(255) UTF8,
	CAMPAIGN_ID DECIMAL(18),
	CAMPAIGN_NAME VARCHAR(255) UTF8,
	CLICKS DECIMAL(18),
	CPC DECIMAL(18,10),
	CPM DECIMAL(18,10),
	CPP DECIMAL(18,10),
	CTR DECIMAL(18,10),
	DATE_START DATE,
	DATE_END DATE,
	FREQUENCY DECIMAL(18,10),
	IMPRESSIONS DECIMAL(18),
	INLINE_LINK_CLICK_CTR DECIMAL(18,10),
	INLINE_LINK_CLICKS DECIMAL(18),
	OBJECTIVE VARCHAR(100) UTF8,
	REACH DECIMAL(18),
	SPEND DECIMAL(18,2),
	TOTAL_ACTION_VALUE DECIMAL(18)
)
/

create or replace table MARKETING_ETL_ERRORS
(
	ETL_DATE TIMESTAMP,
	FILE_NAME VARCHAR(255) UTF8,
	ERROR_MSG VARCHAR(255) UTF8
)
/

create or replace view CU_ONLINE_MARKETING_STG.LINKEDIN_ADS_VIEW as
	(
		select
			ads.AD_DATE,
			camp.ID as 'CAMPAIGN_ID',
			left(camp.CAMPAIGN_NAME, 4) as 'PROGRAM',
			camp.CAMPAIGN_NAME,
			camp.CREATED_DATE,
			camp.COST_TYPE,
			camp.DAILY_BUDGET,
			camp.OBJECTIVE_TYPE,
			camp.CAMPAIGN_TYPE,
			camp.UNIT_COST_AMOUNT,
			-- camp.START_DATE,
			-- camp.END_DATE,
			ads.CREATIVE_ID,
			ads.CLICKS,
			ads.AD_COMMENTS,
			ads.COMPANY_PAGE_CLICKS,
			ads.COST,
			ads.IMPRESSIONS,
			ads.FOLLOWS,
			ads.SHARES,
			ads.VIRAL_CLICKS,
			ads.VIRAL_FOLLOWS,
			ads.VIRAL_IMPRESSIONS,
			ads.VIRAL_COMMENTS,
			ads.VIRAL_SHARES

		from
			CU_ONLINE_MARKETING_STG.LINKEDIN_CAMPAIGN_CREATIVE_LINK l
			join CU_ONLINE_MARKETING_STG.LINKEDIN_CAMPAIGNS_UPDATED camp
				on camp.id = l.CAMPAIGN_ID
			join CU_ONLINE_MARKETING_STG.LINKEDIN_ADS ads
				on ads.CREATIVE_ID = l.CREATIVE_ID
	)
/

create or replace view CU_ONLINE_MARKETING_STG.HUBSPOT_CONTACTS_VIEW as

  ( select
    i.VID,
    i.FIRST_NAME,
    i.LAST_NAME,
    a.ACADEMIC_PROGRAM,
    i.CREATED_DATE ,
    i.LIFECYCLE_STAGE,
    i.LIFECYCLE_STAGE_DATE,
    i.CONVERSION_NAME,
    i.CONVERSION_DATE,
    i.NUM_PAGE_VIEWS,
    i.HOME_CITY,
    i.HOME_STATE,
    i.HOME_ZIP,
    i.HUBSPOT_SCORE,
    i.TWITTER,
    i.LINKED_IN,
    i.LINKED_IN_BIO,
    i.PHONE,
    i.SPECIALIZATIONS,
    i.EMAIL,
    i.CU_EMAIL,
    i.LEAD_STATUS,
    i.EMAILS_SINCE_LAST_ENGAGEMENT,
    i.RESIDENCY,
    i.CU_ADMIT,
    i.CLOSED_DATE,
    i.LAST_MODIFIED_DATE,
    i.KLOUTSCORE,
    i.IMPORT_DATE
  from
    CU_ONLINE_MARKETING_STG.HUBSPOT_CONTACTS_INFO i
    left join CU_ONLINE_MARKETING_STG.HUBSPOT_CONTACTS_ACADEMIC_PROGRAMS a
      on i.VID = a.VID
    join CU_ONLINE_MARKETING_STG.HUBSPOT_CONTACTS c
      on c.vid = i.VID

	)
/
