-- we don't know how to generate schema CU_ONLINE_MARKETING (class Schema) :(
create or replace table GOOGLE_ADWORDS
(
	AD_DATE DATE,
	CAMPAIGN_ID DECIMAL(18),
	CAMPAIGN_NAME VARCHAR(100) UTF8,
	ADGROUP_ID DECIMAL(18),
	ADGROUP_NAME VARCHAR(100) UTF8,
	ADGROUP_STATUS VARCHAR(50) UTF8,
	AD_TYPE VARCHAR(50) UTF8,
	DESCRIPTION VARCHAR(255) UTF8,
	HEADLINE VARCHAR(255) UTF8,
	AD_ID DECIMAL(18),
	AD_STATUS VARCHAR(50) UTF8,
	CLICKS DECIMAL(18),
	CONVERSION_RATE DECIMAL(18,10),
	CONVERSIONS DECIMAL(18),
	COST DECIMAL(18,2),
	COST_PER_CONVERSION DECIMAL(18,10),
	CLICK_THROUGH_RATE DECIMAL(18,10),
	ENGAGEMENT_RATE DECIMAL(18,10),
	ENGAGEMENTS DECIMAL(18),
	IMPRESSIONS DECIMAL(18),
	INTERACTIONS DECIMAL(18),
	PERCENT_INTERACTIONS_NEW DECIMAL(18,10),
	VIDEO_VIEWS DECIMAL(18)
)
/

create or replace table FACEBOOK_ADS
(
	PROGRAM_NAME VARCHAR(4) UTF8,
	AD_DATE DATE,
	ACCOUNT_ID DECIMAL(18),
	CAMPAIGN_ID DECIMAL(18),
	CAMPAIGN_NAME VARCHAR(255) UTF8,
	AD_ID DECIMAL(18),
	ADSET_ID DECIMAL(18),
	ADSET_NAME VARCHAR(255) UTF8,
	CLICKS DECIMAL(18),
	CPC DECIMAL(18,10),
	CPM DECIMAL(18,10),
	CPP DECIMAL(18,10),
	CTR DECIMAL(18,10),
	FREQUENCY DECIMAL(18,10),
	IMPRESSIONS DECIMAL(18),
	INLINE_LINK_CLICK_CTR DECIMAL(18,10),
	INLINE_LINK_CLICKS DECIMAL(18),
	OBJECTIVE VARCHAR(100) UTF8,
	REACH DECIMAL(18),
	SOCIAL_CLICKS DECIMAL(18),
	SOCIAL_IMPRESSIONS DECIMAL(18),
	SOCIAL_REACH DECIMAL(18),
	SOCIAL_SPEND DECIMAL(18,2),
	SPEND DECIMAL(18,2),
	TOTAL_ACTION_VALUE DECIMAL(18),
	TOTAL_ACTIONS DECIMAL(18),
	UNIQUE_CLICKS DECIMAL(18),
	UNIQUE_CTR DECIMAL(18,10),
	UNIQUE_SOCIAL_CLICKS DECIMAL(18)
)
/

create or replace table LINKEDIN_ADS
(
	AD_DATE DATE,
	CAMPAIGN_ID DECIMAL(18),
	PROGRAM VARCHAR(4) UTF8,
	CAMPAIGN_NAME VARCHAR(255) UTF8,
	CREATED_DATE DATE,
	COST_TYPE VARCHAR(10) UTF8,
	DAILY_BUDGET DECIMAL(18,2),
	OBJECTIVE_TYPE VARCHAR(100) UTF8,
	CAMPAIGN_TYPE VARCHAR(100) UTF8,
	UNIT_COST_AMOUNT DECIMAL(18,2),
	START_DATE DATE,
	END_DATE DATE,
	CREATIVE_ID DECIMAL(18),
	CLICKS DECIMAL(18),
	AD_COMMENTS DECIMAL(18),
	COMPANY_PAGE_CLICKS DECIMAL(18),
	COST DECIMAL(18,2),
	IMPRESSIONS DECIMAL(18),
	FOLLOWS DECIMAL(18),
	SHARES DECIMAL(18),
	VIRAL_CLICKS DECIMAL(18),
	VIRAL_FOLLOWS DECIMAL(18),
	VIRAL_IMPRESSIONS DECIMAL(18),
	VIRAL_COMMENTS DECIMAL(18),
	VIRAL_SHARES DECIMAL(18)
)
/

create or replace table ASK_NICELY_RESPONSES
(
	RESPONSE_ID DECIMAL(18),
	RESPONSE_DATE DATE,
	NAME VARCHAR(100) UTF8,
	SEGMENT VARCHAR(100) UTF8,
	EMAIL VARCHAR(100) UTF8,
	ANSWER DECIMAL(18)
)
/

create or replace table HUBSPOT_SOCIAL_POSTS
(
	POST_ID DECIMAL(18),
	CAMPAIGN VARCHAR(100) UTF8,
	POST_CHANNEL VARCHAR(50) UTF8,
	CREATED_DATE DATE,
	POST_TITLE VARCHAR(255) UTF8,
	POST_URL VARCHAR(255) UTF8,
	CLICKS DECIMAL(18),
	LIKES DECIMAL(18),
	RETWEETS DECIMAL(18),
	REPLIES DECIMAL(18),
	ITERACTIONS DECIMAL(18)
)
/

create or replace table HUBSPOT_CONTACTS
(
	VID DECIMAL(18),
	FIRST_NAME VARCHAR(100) UTF8,
	LAST_NAME VARCHAR(100) UTF8,
	ACADEMIC_PROGRAM VARCHAR(100) UTF8,
	CREATED_DATE DATE,
	LIFECYCLE_STAGE VARCHAR(100) UTF8,
	LIFECYCLE_STAGE_DATE DATE,
	CONVERSION_NAME VARCHAR(255) UTF8,
	CONVERSION_DATE DATE,
	NUM_PAGE_VIEWS DECIMAL(18),
	HOME_CITY VARCHAR(100) UTF8,
	HOME_STATE VARCHAR(100) UTF8,
	HOME_ZIP VARCHAR(10) UTF8,
	HUBSPOT_SCORE DECIMAL(18),
	TWITTER VARCHAR(100) UTF8,
	LINKED_IN VARCHAR(100) UTF8,
	LINKED_IN_BIO VARCHAR(255) UTF8,
	PHONE VARCHAR(50) UTF8,
	SPECIALIZATIONS VARCHAR(255) UTF8,
	EMAIL VARCHAR(100) UTF8,
	CU_EMAIL VARCHAR(100) UTF8,
	LEAD_STATUS VARCHAR(100) UTF8,
	EMAILS_SINCE_LAST_ENGAGEMENT VARCHAR(100) UTF8,
	RESIDENCY VARCHAR(50) UTF8,
	CU_ADMIT VARCHAR(50) UTF8,
	CLOSED_DATE DATE,
	LAST_MODIFIED_DATE DATE,
	KLOUTSCORE VARCHAR(50) UTF8,
	IMPORT_DATE DATE
)
/

create or replace view CU_ONLINE_MARKETING.HUBSPOT_WITH_ASK_NICELY_VIEW as
  (
    select distinct *
    from
      (
        select
          hsc.VID,
          hsc.LAST_NAME,
          hsc.FIRST_NAME,
          hsc.ACADEMIC_PROGRAM,
          hsc.LIFECYCLE_STAGE,
          hsc.LIFECYCLE_STAGE_DATE,
          hsc.CONVERSION_NAME,
          hsc.NUM_PAGE_VIEWS,
          hsc.PHONE,
          upper(hsc.EMAIL) as 'EMAIL',
          upper(hsc.CU_EMAIL) as 'CU_EMAIL',
          hsc.LEAD_STATUS,
          hsc.RESIDENCY,
          hsc.CU_ADMIT,
          hsc.LAST_MODIFIED_DATE,
          hsc.KLOUTSCORE,
          an.SEGMENT,
          an.RESPONSE_DATE,
          an.ANSWER
        from
          CU_ONLINE_MARKETING.HUBSPOT_CONTACTS hsc
          left join CU_ONLINE_MARKETING.ASK_NICELY_RESPONSES an
            on upper(hsc.CU_EMAIL) = upper(an.EMAIL)
        union all
        select
          hsc.VID,
          hsc.LAST_NAME,
          hsc.FIRST_NAME,
          hsc.ACADEMIC_PROGRAM,
          hsc.LIFECYCLE_STAGE,
          hsc.LIFECYCLE_STAGE_DATE,
          hsc.CONVERSION_NAME,
          hsc.NUM_PAGE_VIEWS,
          hsc.PHONE,
          upper(hsc.EMAIL) as 'EMAIL',
          upper(hsc.CU_EMAIL) as 'CU_EMAIL',
          hsc.LEAD_STATUS,
          hsc.RESIDENCY,
          hsc.CU_ADMIT,
          hsc.LAST_MODIFIED_DATE,
          hsc.KLOUTSCORE,
          an.SEGMENT,
          an.RESPONSE_DATE,
          an.ANSWER
        from
          CU_ONLINE_MARKETING.HUBSPOT_CONTACTS hsc
          left join CU_ONLINE_MARKETING.ASK_NICELY_RESPONSES an
            on upper(hsc.EMAIL) = upper(an.EMAIL)

      )
  )
/

create or replace view CU_ONLINE_MARKETING.MARKETING_DAILY_SPEND_VIEW as
(
  select
    'Paid' as 'PAID_SOCIAL',
    'Google Adwords' as 'MARKETING_PLATFORM',
    AD_DATE,
    CASE WHEN CAMPAIGN_NAME = 'Master Criminal Justice MCJ' OR CAMPAIGN_NAME = 'MC J' THEN 'MCJ' ELSE CAMPAIGN_NAME END AS 'PROGRAM',
    ADGROUP_NAME as 'CAMPAIGN',
    HEADLINE,
    DESCRIPTION,
    AD_ID,
    CLICKS,
    CONVERSIONS,
    COST,
    IMPRESSIONS,
    CAST(CASE WHEN (CLICKS = 0 or IMPRESSIONS = 0) THEN 0 ELSE (CLICKS / IMPRESSIONS) END as DECIMAL(10,3)) as 'CLICKS_PER_IMPRESSIONS',
    CAST(CASE WHEN (COST = 0 or CLICKS = 0) THEN 0 ELSE (COST /CLICKS) END as DECIMAL(10,2)) as 'COST_PER_CLICK'
from CU_ONLINE_MARKETING.GOOGLE_ADWORDS
where IMPRESSIONS > 0
union all
select
    'Paid' as 'PAID_SOCIAL',
    'LinkedIn' as 'MARKETING_PLATFORM',
    AD_DATE,
    CASE
      WHEN PROGRAM = 'Master Criminal Justice MCJ' OR PROGRAM = 'MC J' THEN 'MCJ'
      WHEN PROGRAM = 'CUON' OR PROGRAM = 'CU Online' THEN 'CU Online'
    ELSE PROGRAM END AS 'PROGRAM',
    CAMPAIGN_NAME as 'CAMPAIGN',
    CAMPAIGN_NAME,
    '',
    CREATIVE_ID,
    CLICKS,
    '',
    COST,
    IMPRESSIONS,
    CAST(CASE WHEN (CLICKS = 0 or IMPRESSIONS = 0) THEN 0 ELSE (CLICKS / IMPRESSIONS) END as DECIMAL(10,3)) as 'CLICKS_PER_IMPRESSIONS',
    CAST(CASE WHEN (COST = 0 or CLICKS = 0) THEN 0 ELSE (COST /CLICKS) END as DECIMAL(10,2)) as 'COST_PER_CLICK'
from CU_ONLINE_MARKETING.LINKEDIN_ADS
where IMPRESSIONS > 0
union all
select
   'Paid' as 'PAID_SOCIAL',
   'Facebook' as 'MARKETING_PLATFORM',
    AD_DATE,
    CASE
      WHEN PROGRAM_NAME = 'CUON' THEN 'CU Online'
      WHEN PROGRAM_NAME = 'Master Criminal Justice MCJ' OR PROGRAM_NAME = 'M CJ' THEN 'MCJ' ELSE PROGRAM_NAME
    END AS 'PROGRAM',
    ADSET_NAME as 'CAMPAIGN',
    ADSET_NAME,
    '',
    AD_ID,
    CLICKS,
    TOTAL_ACTIONS,
    SPEND,
    IMPRESSIONS,
    CAST(CASE WHEN (CLICKS = 0 or IMPRESSIONS = 0) THEN 0 ELSE (CLICKS / IMPRESSIONS) END as DECIMAL(10,3)) as 'CLICKS_PER_IMPRESSIONS',
    CAST(CASE WHEN (SPEND = 0 or CLICKS = 0) THEN 0 ELSE (SPEND /CLICKS) END as DECIMAL(10,2)) as 'COST_PER_CLICK'
from CU_ONLINE_MARKETING.FACEBOOK_ADS
where IMPRESSIONS > 0
union all
select
    'Social' as 'PAID_SOCIAL',
    POST_CHANNEL as 'MARKETING_PLATFORM',
    CREATED_DATE,
    CAMPAIGN,
    CAMPAIGN as 'CAMPAIGN',
    POST_TITLE,
    POST_TITLE as 'Description',
    POST_ID,
    CLICKS,
    '',
    '',
    ITERACTIONS,
    '',
    ''
from CU_ONLINE_MARKETING.HUBSPOT_SOCIAL_POSTS
)
/
